version: "2"
run:
  issues-exit-code: 1
  tests: false
  allow-parallel-runners: true
  concurrency: 4
  go: "1.25"
  modules-download-mode: readonly
issues:
  max-issues-per-linter: 50      # Ограничить вывод
  max-same-issues: 3             # Не показывать одну ошибку 100 раз
  new: false                     # false = проверять весь код, true = только изменения
linters:
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - goconst
    - gocritic
    - gosec
    - importas
    - ireturn
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
  disable:
    - asasalint
    - asciicheck
    - containedctx
    - cyclop
    - decorder
    - depguard
    - dogsled
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - grouper
    - interfacebloat
    - lll
    - maintidx
    - nilnil
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    errcheck:
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - (io.ReadCloser).Close
        - (*net/http.Response).Body.Close
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - importShadow
        - emptyStringTest
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    revive:
      rules:
        - name: package-comments
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: declaration of "err" shadows declaration
      - linters:
          - err113
        text: do not define dynamic errors, use wrapped static errors instead
      - linters:
          - gocritic
        text: 'commentedOutCode: may want to remove commented-out code'
      - path: (.+)\.go$
        text: ST1000
    paths:
      - \.pb\.go$
      - \.pb\.gw\.go$
      - consumer/http/docs
      - mock*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - \.pb\.go$
      - \.pb\.gw\.go$
      - consumer/http/docs
      - mock*
      - third_party$
      - builtin$
      - examples$
