// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockevateamclient

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	req "github.com/imroc/req/v3"
)

// HTTPClient is an autogenerated mock type for the HTTPClient type
type HTTPClient struct {
	mock.Mock
}

type HTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *HTTPClient) EXPECT() *HTTPClient_Expecter {
	return &HTTPClient_Expecter{mock: &_m.Mock}
}

// Post provides a mock function with given fields: ctx, body, url
func (_m *HTTPClient) Post(ctx context.Context, body []byte, url string) (*req.Response, error) {
	ret := _m.Called(ctx, body, url)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *req.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string) (*req.Response, error)); ok {
		return rf(ctx, body, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string) *req.Response); ok {
		r0 = rf(ctx, body, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*req.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string) error); ok {
		r1 = rf(ctx, body, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPClient_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type HTTPClient_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - ctx context.Context
//   - body []byte
//   - url string
func (_e *HTTPClient_Expecter) Post(ctx interface{}, body interface{}, url interface{}) *HTTPClient_Post_Call {
	return &HTTPClient_Post_Call{Call: _e.mock.On("Post", ctx, body, url)}
}

func (_c *HTTPClient_Post_Call) Run(run func(ctx context.Context, body []byte, url string)) *HTTPClient_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string))
	})
	return _c
}

func (_c *HTTPClient_Post_Call) Return(_a0 *req.Response, _a1 error) *HTTPClient_Post_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HTTPClient_Post_Call) RunAndReturn(run func(context.Context, []byte, string) (*req.Response, error)) *HTTPClient_Post_Call {
	_c.Call.Return(run)
	return _c
}

// NewHTTPClient creates a new instance of HTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPClient {
	mock := &HTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
