// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockevateamclient

import mock "github.com/stretchr/testify/mock"

// Metrics is an autogenerated mock type for the Metrics type
type Metrics struct {
	mock.Mock
}

type Metrics_Expecter struct {
	mock *mock.Mock
}

func (_m *Metrics) EXPECT() *Metrics_Expecter {
	return &Metrics_Expecter{mock: &_m.Mock}
}

// RecordRequestDuration provides a mock function with given fields: status, method, host, function, duration
func (_m *Metrics) RecordRequestDuration(status int, method string, host string, function string, duration float64) {
	_m.Called(status, method, host, function, duration)
}

// Metrics_RecordRequestDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordRequestDuration'
type Metrics_RecordRequestDuration_Call struct {
	*mock.Call
}

// RecordRequestDuration is a helper method to define mock.On call
//   - status int
//   - method string
//   - host string
//   - function string
//   - duration float64
func (_e *Metrics_Expecter) RecordRequestDuration(status interface{}, method interface{}, host interface{}, function interface{}, duration interface{}) *Metrics_RecordRequestDuration_Call {
	return &Metrics_RecordRequestDuration_Call{Call: _e.mock.On("RecordRequestDuration", status, method, host, function, duration)}
}

func (_c *Metrics_RecordRequestDuration_Call) Run(run func(status int, method string, host string, function string, duration float64)) *Metrics_RecordRequestDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(string), args[3].(string), args[4].(float64))
	})
	return _c
}

func (_c *Metrics_RecordRequestDuration_Call) Return() *Metrics_RecordRequestDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *Metrics_RecordRequestDuration_Call) RunAndReturn(run func(int, string, string, string, float64)) *Metrics_RecordRequestDuration_Call {
	_c.Run(run)
	return _c
}

// NewMetrics creates a new instance of Metrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *Metrics {
	mock := &Metrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
